# springboot项目对外暴漏的端口（web项目就是访问端口）
server:
  port: 9001

spring:
  data:
    mongodb:
      host: 192.168.66.129
      port: 27017
      database: car-comment

dubbo:
    application:
      # 项目名称，用于计算服务的依赖关系。（区分不同项目的服务）
      name: dubbo-service-comment
    # 指定zk注册中心地址
    registry:
      address: zookeeper://192.168.66.129:2181
    protocol:
      # 对外暴漏的服务使用的协议：dubbo协议, 官网推荐
      name: dubbo
      # 对外暴漏服务的端口
      port: 20881
    # dubbo包扫描，会扫描dubbo提供的@Service注解
    scan:
      base-packages: com.first.group.comment