server:
  port: 9002

spring:
  #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.66.129:3306/car_service_manage?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    mongodb:
      host: 192.168.66.129
      port: 27017
      database: car-comment

dubbo:
  # 项目名称，用于计算服务的依赖关系。（区分不同项目的服务）
  application:
    name: order-web-comment
  # 注册中心地址
  registry:
    address: zookeeper://192.168.66.129:2181


minio:
  accessKey: minio
  secretKey: minio123
  bucket: mainbody
  endpoint: http://192.168.66.129:9000
  readPath: http://192.168.66.129:9000