# springboot项目对外暴漏的端口（web项目就是访问端口）
server:
  port: 9003

spring:
  #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.66.128:3306/pc_Parts_one?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root

  data:
    mongodb:
      host: 192.168.66.128
      port: 27017
      database: car-parts

  #mybatis的扫描的xml
mybatis:
  mapper-locations: classpath:com.first.group.parts.mapper/*.xml
  configuration.mapUnderscoreToCamelCase: true

 

      #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dubbo:
  application:
    # 项目名称，用于计算服务的依赖关系。（区分不同项目的服务）
    name: dubbo-service-parts
  # 指定zk注册中心地址
  registry:
    address: zookeeper://192.168.66.128:2181
  protocol:
    # 对外暴漏的服务使用的协议：dubbo协议, 官网推荐
    name: dubbo
    # 对外暴漏服务的端口
    port: 20882
  # dubbo包扫描，会扫描dubbo提供的@Service注解
  scan:
    base-packages: com.first.group.parts



#日志显示SQL
logging.level:
  com.first.group.parts.mapper: debug