# springboot项目对外暴漏的端口（web项目就是访问端口）
server:
  port: 9011

spring:
  data:
    mongodb:
      host: 192.168.66.128
      port: 27017
      database: car-comment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.66.128:3306/order?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root

dubbo:
  application:
    # 项目名称，用于计算服务的依赖关系。（区分不同项目的服务）
    name: dubbo-service-order
    # 指定zk注册中心地址
  registry:
    address: zookeeper://192.168.66.128:2181
  protocol:
    # 对外暴漏的服务使用的协议：dubbo协议, 官网推荐
    name: dubbo
    # 对外暴漏服务的端口
    port: 20884
    # dubbo包扫描，会扫描dubbo提供的@Service注解
  scan:
    base-packages: com.first.group.order

mybatis:
  type-aliases-package: com.first.group.order.pojos
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath*:com/first/group/mapper/*.xml
minio:
  accessKey: minio
  secretKey: minio123
  bucket: mainbody
  endpoint: http://192.168.66.128:9000
  readPath: http://192.168.66.128:9000
